### ISSUE TITLE
GET board API : list, item 중 빈 항목이 있을 때 not found 반환 이슈

### ISSUE THREAD

**Issue by eunjung-jenny** [woowa-techcamp-2020/todo-12#20]
리스트 길이로 체크를 하기 때문에 board 가 존재함에도 list 가 존재하지 않는 경우 board 를 찾지 못했다는 에러 메세지 반환

**Comment by jungcome7** [comment]
inner join 대신 left join 사용해서 list.id = null인 board를 반환하는 방법은 어때요? 일단 적용해서 풀리퀘 올렸어요.
